name: 'streaming'
version: '1.0.0'
config-version: 2

profile: 'streaming'

model-paths: ["models"]
seed-paths: ["seeds"]

models:
  streaming:
    staging:
      +materialized: view
    marts:
      +materialized: table
